const mongoose = require('mongoose')
const jobSchema = new mongoose.Schema(
    {
        companyName:{
            type:String,
            required:true
        },
        logoUrl:{
            type:String,
            required:true
        },
        jobPosition:{
            type:String,
            required:true
        },
        monthlySalary:{
            type:String,
            required:true
        },
        jobType:{
            type:String,
            enum:['Full-time','Part-time','Contract','Freelance'],
            default:'Full-time'
        },
        remote:{
            type:String,
            required:true
        },
        location:{
            type:String,
            required:true
        },
        jobDescription:{
            type:String,
            required:true
        },
        aboutCompany:{
            type:String,
            required:true
        },
        skills:{
            type:Array,
            required:true
        },
        information:{
            type:String,
            required:true
        },
        creator:{
            type:String,
            required:true
        },
        userId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"User"
        }
    }
)

module.exports = mongoose.model("Job",jobSchema);